apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  tags:
    - ${{ values.env | dump }}
spec:
  type: service
  owner: team-dhruv
  lifecycle: ${{ values.env }}
